puts "Creating"
print "hello world"
print " is awesome"
puts "will print out whatever you specify and then a new line"
print " will put out whatevr you specify "
print "ruby executes line by line in order"